### ISSUE TITLE
Starter should find already running subprocesses

### ISSUE THREAD

**Issue by neunhoef** [arangodb-helper/ArangoDBStarter#6]
If the starter was crashed (like with kill -9 on linux) and is restarted, it gets into an endless loop because the subprocesses are still running. We should probably detect at startup that there are already arangod processes running on the planned ports, see whether they are alive and adopt them in this case. Furthermore, if startup of the subprocesses fails very quickly a certain number of times, the starter should give up or at least do an exponential backoff strategy.

**Comment by ewoutp** [comment]
This gets even more complicated when servers are running in docker container.

- Container may exist, but not really running 
- Another contain may exist that has claimed the port a server wants to use 
- Container may be fully functional 
...

Let's first define which scenario's make sense and we want to cover.

**Comment by neunhoef** [comment]
I was thinking of a very simple thing that simply checks /_api/version once on the address and port and "adopted" the process or container if it is already there. This would already prevent a lot of cases in which a new instance cannot be started because the port is already taken.
