### ISSUE TITLE
Delay in startup of the first three machines

### ISSUE THREAD

**Issue by neunhoef** [arangodb-helper/ArangoDBStarter#7]
The starter waits until three machines have registered (including the master) and then starts all processes in quick succession. This creates a race for the names "DBServer0001" and "Coordinator0001". It would be better for users if the starter would delay the startup on machines 2 and 3 slightly, such that the numbering would always be consistent. This is only necessary on the first startup, restarts are fine since the names are taken then.

**Comment by ewoutp** [comment]
Why are the servers picking such "well known" names instead of picking just a random ID?

**Comment by neunhoef** [comment]
We actually use UUIDs internally. The short names are solely for the purposes of the UI, where we considered the UUIDs to be "ugly". The names "DBServer0001" are also a form of backward compatibility.

**Comment by ewoutp** [comment]
We want to allow renaming the names after creating.
Closing the issue here.
